// Generated from makes_and_models.json — originally auto-generated.
// Manually extended with LATAM/Colombia market makes (RENAULT, VOLKSWAGEN, CHERY, etc.)
// Source JSON and generate script no longer present in repo; this file is now the source of truth.

export const MAKES: string[] = [
  "ACURA",
  "ALFA ROMEO",
  "AM GENERAL",
  "ASTON MARTIN",
  "AUDI",
  "BENTLEY",
  "BMW",
  "BYD",
  "BUGATTI",
  "BUICK",
  "CADILLAC",
  "CHERY",
  "CHEVROLET",
  "CHRYSLER",
  "CITROEN",
  "DAEWOO",
  "DAIHATSU",
  "DFSK",
  "DAIMLER",
  "DATSUN",
  "DELOREAN",
  "DODGE",
  "FERRARI",
  "FIAT",
  "FISKER",
  "FORD",
  "GEELY",
  "GEO",
  "GMC",
  "GWM",
  "HONDA",
  "HAVAL",
  "HUMMER",
  "HYUNDAI",
  "INFINITI",
  "ISUZU",
  "JAC",
  "JAGUAR",
  "JEEP",
  "KARMA",
  "KIA",
  "LAMBORGHINI",
  "LAND ROVER",
  "LEXUS",
  "LINCOLN",
  "LIFAN",
  "LOTUS",
  "LUCID",
  "MAHINDRA",
  "MASERATI",
  "MAYBACH",
  "MAZDA",
  "MCLAREN",
  "MERCEDES-BENZ",
  "MERCURY",
  "MINI",
  "MITSUBISHI",
  "NISSAN",
  "OLDSMOBILE",
  "PETERBILT",
  "PEUGEOT",
  "RENAULT",
  "PLYMOUTH",
  "PONTIAC",
  "PORSCHE",
  "RAM",
  "RIVIAN",
  "ROLLS-ROYCE",
  "SAAB",
  "SATURN",
  "SEAT",
  "SKODA",
  "SSANGYONG",
  "SHELBY",
  "SMART",
  "SPYKER",
  "SUBARU",
  "SUZUKI",
  "TESLA",
  "TOYOTA",
  "TRIUMPH",
  "VOLKSWAGEN",
  "VOLVO",
  "YUGO"
]

export const MODELS_BY_MAKE: Record<string, string[]> = {
  "ACURA": [
    "CL",
    "ILX",
    "Integra",
    "Legend",
    "MDX",
    "NSX",
    "RDX",
    "RL",
    "RLX",
    "RSX",
    "SLX",
    "TL",
    "TLX",
    "TSX",
    "Vigor",
    "ZDX"
  ],
  "ALFA ROMEO": [
    "164",
    "4C",
    "8C Competizione Spider",
    "GTV6",
    "Giulia (952)",
    "Milano",
    "Spider",
    "Stelvio",
    "Tonale"
  ],
  "AM GENERAL": [
    "MV-1"
  ],
  "ASTON MARTIN": [
    "DB11",
    "DB12",
    "DB7",
    "DB9",
    "DBS",
    "DBX",
    "Lagonda",
    "Rapide",
    "V12 Vantage",
    "V8",
    "V8 Vantage",
    "Valiant",
    "Valour",
    "Vanquish",
    "Vanquish Zagato",
    "Vantage",
    "Virage"
  ],
  "AUDI": [
    "100",
    "200",
    "4000",
    "5000",
    "80",
    "90",
    "A3",
    "A4",
    "A4 allroad",
    "A5",
    "A6",
    "A6 allroad",
    "A7",
    "A7 e",
    "A8",
    "A8 L",
    "A8 L e",
    "A8 e",
    "Cabriolet",
    "Coupe",
    "Q3",
    "Q4",
    "Q5",
    "Q5 e",
    "Q6",
    "Q7",
    "Q8",
    "R8",
    "RS 3",
    "RS 4",
    "RS 5",
    "RS 6",
    "RS 6 Avant",
    "RS 7",
    "RS Q8",
    "RS e-tron GT",
    "S3",
    "S4",
    "S5",
    "S6",
    "S7",
    "S8",
    "SQ5",
    "SQ6",
    "SQ7",
    "SQ8",
    "TT",
    "TT RS",
    "TTS",
    "V8",
    "allroad",
    "e-tron",
    "e-tron GT",
    "e-tron Sportback"
  ],
  "BENTLEY": [
    "ARMOURED ARNAGE",
    "Arnage",
    "Azure",
    "Bentayga",
    "Brooklands",
    "Continental",
    "Eight",
    "Flying Spur",
    "Mulsanne",
    "Roll Royce Silver Seraph",
    "Rolls-Royce Park Ward",
    "Turbo"
  ],
  "BMW": [
    "128i",
    "135i",
    "1M",
    "228",
    "228i",
    "230i",
    "318i",
    "318iC",
    "318iS",
    "318ti",
    "320i",
    "323i",
    "323iC",
    "323is",
    "325/325e",
    "325/325eS",
    "325Ci",
    "325i",
    "325i/325is",
    "325iC",
    "325iS",
    "325ix",
    "325xi",
    "328Ci",
    "328d",
    "328i",
    "328iC",
    "328iS",
    "328xi",
    "330Ci",
    "330e",
    "330i",
    "330xi",
    "335",
    "335d",
    "335i",
    "335is",
    "335xi",
    "340i",
    "428i",
    "430i",
    "435i",
    "440i",
    "524td",
    "525i",
    "525iA",
    "525xi",
    "528e",
    "528i",
    "528xi",
    "530e",
    "530i",
    "530iA",
    "530xi",
    "533i",
    "535d",
    "535i",
    "535i/535is",
    "535xi",
    "540d",
    "540i",
    "540iA",
    "545i",
    "550e",
    "550i",
    "633 csi",
    "635CSi",
    "640i",
    "640xi",
    "645Ci",
    "645i",
    "650i",
    "650i / ALPINA B6",
    "650i / B6",
    "650xi",
    "730i",
    "733i",
    "735i",
    "735iL",
    "740Li",
    "740e",
    "740i",
    "740iL",
    "745Le",
    "745Li",
    "745e",
    "745i",
    "750Li",
    "750Li / ALPINA B7",
    "750Lxi",
    "750Lxi / ALPINA B7",
    "750e",
    "750i",
    "750i / ALPINA B7",
    "750i / B7",
    "750iL",
    "750xi",
    "750xi / ALPINA B7",
    "760Li",
    "760i",
    "840Ci",
    "840i",
    "850CSi",
    "850Ci",
    "850i",
    "ALPINA B8",
    "ActiveE",
    "ActiveHybrid 3",
    "ActiveHybrid 5",
    "ActiveHybrid 7",
    "Alpina",
    "B7",
    "L7",
    "M2",
    "M235i",
    "M240i",
    "M3",
    "M340i",
    "M3Ci",
    "M4",
    "M440i",
    "M5",
    "M550i",
    "M6",
    "M760Li",
    "M760i",
    "M8",
    "M850i",
    "X1",
    "X2",
    "X3",
    "X4",
    "X5",
    "X6",
    "X7",
    "XM",
    "Z3",
    "Z4",
    "Z8",
    "i3",
    "i4",
    "i5",
    "i7",
    "i8",
    "iX"
  ],
  "BUGATTI": [
    "Chiron",
    "Chiron Pur Sport",
    "Chiron Supersport",
    "EB110",
    "Veyron"
  ],
  "BUICK": [
    "Allure",
    "Cascada",
    "Century",
    "Coachbuilder",
    "Electra",
    "Enclave",
    "Encore",
    "Encore GX",
    "Envision",
    "Envista",
    "Incomplete",
    "LaCrosse",
    "LeSabre",
    "Lucerne",
    "Park Avenue",
    "Rainier",
    "Reatta",
    "Regal",
    "Regal TourX",
    "Rendezvous",
    "Riviera",
    "Roadmaster",
    "Skyhawk",
    "Skylark",
    "Somerset",
    "Terraza",
    "Verano"
  ],
  "CADILLAC": [
    "60 Special",
    "ATS",
    "Allante",
    "Brougham",
    "CT4",
    "CT5",
    "CT6",
    "CTS",
    "Catera",
    "Celestiq",
    "Cimarron",
    "Commercial Chassis",
    "DTS",
    "Deville",
    "ELR",
    "Eldorado",
    "Escalade",
    "Escalade ESV",
    "Escalade IQ",
    "Fleetwood",
    "Hearse",
    "Limousine",
    "Lyriq",
    "Optiq",
    "SRX",
    "STS",
    "Seville",
    "Vistiq",
    "XLR",
    "XT4",
    "XT5",
    "XT6",
    "XTS"
  ],
  "CHEVROLET": [
    "3 ton",
    "Alero",
    "Aluminum Tilt",
    "Astro Van",
    "Avalanche",
    "Aveo",
    "B7",
    "Beretta",
    "Blazer",
    "Blazer EV",
    "Bolt EUV",
    "Bolt EV",
    "BrightDrop 400",
    "BrightDrop 400, BrightDrop 600",
    "BrightDrop 600",
    "Bus Chassis",
    "C/K Pickup",
    "C5",
    "C6",
    "C7",
    "Camaro",
    "Caprice",
    "Caprice Police Vehicle",
    "Captiva Sport",
    "Cavalier",
    "Celebrity",
    "Chevette",
    "Citation",
    "City Express",
    "Cobalt",
    "Colorado",
    "Corsica",
    "Corvette",
    "Cruze",
    "Cruze Limited",
    "Cutaway Chassis",
    "El Camino",
    "Epica",
    "Equinox",
    "Equinox EV",
    "Express",
    "Forward Control",
    "G-Series",
    "GMT-400",
    "Geo Prizm",
    "Geo Spectrum",
    "Geo Sprint",
    "HHR",
    "Hearse/Limo",
    "Hearse/Limo Commercial Chassis",
    "Heavy Conventional",
    "Hi-Cube",
    "Impala",
    "Impala Limited",
    "Kalos",
    "LUV",
    "Lumina",
    "Lumina APV",
    "Malibu",
    "Malibu Classic",
    "Malibu Limited",
    "Matiz",
    "Metro",
    "Military Truck",
    "Monte Carlo",
    "Motorhome Chassis",
    "Nova",
    "Onix",
    "Optra",
    "Orlando",
    "P - Series",
    "P6S",
    "R Conventional",
    "S-10 Blazer",
    "S-10 Pickup",
    "S6",
    "S7",
    "SS",
    "SSR",
    "Silverado",
    "Silverado EV",
    "Silverado HD",
    "Silverado LD",
    "Silverado LTD",
    "Sonic",
    "Spark",
    "Suburban",
    "Suburban HD",
    "Tahoe",
    "Tracker",
    "Trailblazer",
    "Traverse",
    "Traverse Limited",
    "Trax",
    "U100",
    "Uplander",
    "V Conventional",
    "Venture",
    "Volt"
  ],
  "CHRYSLER": [
    "200",
    "300",
    "300C",
    "Aspen",
    "Caravan",
    "Cirrus",
    "Concorde",
    "Concorde/LHS",
    "Conquest",
    "Cordoba",
    "Crossfire",
    "Daytona",
    "Dynasty",
    "E-CLASS",
    "EXECUTIVE",
    "FIFTH AVENUE",
    "Grand Caravan",
    "Grand Voyager",
    "Imperial",
    "Intrepid",
    "LASER",
    "LHS",
    "LeBaron",
    "NEWPORT",
    "Neon",
    "New Yorker",
    "PT Cruiser",
    "Pacifica",
    "Prowler",
    "SALON",
    "Sebring",
    "Shadow",
    "Stratus",
    "TC",
    "Town and Country",
    "Viper",
    "Vision",
    "Voyager"
  ],
  "DAEWOO": [
    "G2X",
    "LANOS",
    "LEGANZA",
    "Laganza V-car",
    "Leganza V-200 & variants/derivatives",
    "NUBIRA"
  ],
  "DAIHATSU": [
    "Charade",
    "Rocky"
  ],
  "DAIMLER": [
    "DS",
    "DT"
  ],
  "DATSUN": [
    "210",
    "280ZX",
    "310",
    "510"
  ],
  "DELOREAN": [
    "DMC-12"
  ],
  "DODGE": [
    "400",
    "600",
    "ARIES",
    "Avenger",
    "Caliber",
    "Caravan",
    "Caravan/Grand Caravan",
    "Challenger",
    "Charger",
    "Colt",
    "Conquest",
    "D-Series",
    "D50",
    "DIPLOMAT",
    "Dakota",
    "Dart",
    "Daytona",
    "Durango",
    "Dynasty",
    "Grand Caravan",
    "Hornet",
    "Intrepid",
    "Journey",
    "LANCER",
    "Magnum",
    "Mini Ram",
    "Mirada",
    "Monaco",
    "Neon",
    "Nitro",
    "OMNI",
    "RAM 50",
    "RD200 / RD250",
    "Raider",
    "Ram",
    "Ram Chassis Cab",
    "Ram Van",
    "Ram Wagon",
    "Ramcharger",
    "Rampage",
    "Royal Mini Ram Van",
    "ST.REGIS",
    "Shadow",
    "Shelby Charger",
    "Spirit",
    "Sprinter",
    "Stealth",
    "Stratus",
    "Viper",
    "W-Series"
  ],
  "FERRARI": [
    "12Cilindri",
    "12Cilindri Spider",
    "296 GTB",
    "296 GTS",
    "3.2 Mondial",
    "308 Convertible",
    "308GTB",
    "308GTB Quattrovalvole",
    "308GTBi",
    "308GTS",
    "308GTS Quattrovalvole",
    "308GTSi",
    "328",
    "328 GTB",
    "328 GTS",
    "348 Spider",
    "348 tb",
    "348 ts",
    "355 Berlinetta",
    "355 GTS",
    "355 Spider",
    "360 Modena",
    "360 Spider",
    "430 Scuderia",
    "430 Scuderia Spider",
    "456 GT",
    "456 MGT",
    "456 MGTA",
    "458 Italia",
    "458 Speciale",
    "458 Speciale Spider",
    "458 Spider",
    "488 GTB",
    "488 GTS",
    "488 Pista",
    "488 Pista Spider",
    "488 Spider",
    "512 TR",
    "550 Barchetta",
    "550 Maranello",
    "575 M Maranello",
    "599 GTB",
    "599 GTB Fiorano",
    "599 GTO",
    "612 Scaglietti",
    "812 Competizione",
    "812 Competizione A",
    "812 GTS",
    "812 Superfast",
    "California",
    "California T",
    "Challenge Stradale",
    "Daytona SP3",
    "Enzo",
    "F12 Berlinetta",
    "F12 Special Series",
    "F12 tdf (Tour de France)",
    "F164BCB",
    "F355",
    "F40",
    "F430",
    "F430 Coupe",
    "F430 Spider",
    "F50",
    "F60 America",
    "F8 Spider",
    "F8 Tributo",
    "FF",
    "GTC4Lusso",
    "La Ferrari",
    "Mondial 8",
    "Mondial T",
    "Monza SP1/SP2",
    "Portofino",
    "Portofino M",
    "Purosangue",
    "Roma",
    "Roma Spider",
    "SF90 Spider",
    "SF90 Stradale",
    "SF90 XX Spider",
    "SF90 XX Stradale",
    "Testarossa"
  ],
  "FIAT": [
    "124 Spider",
    "500",
    "500L",
    "500X",
    "500e",
    "Brava",
    "Ducato",
    "Freemont",
    "Spider 2000",
    "Strada",
    "X 1/9"
  ],
  "FISKER": [
    "Karma",
    "Nina",
    "Ocean"
  ],
  "FORD": [
    "'34",
    "A8513",
    "A9513",
    "A9522",
    "AT8513",
    "AT9513",
    "AT9522",
    "Aerostar",
    "Aspire",
    "B-750",
    "B600",
    "B6000",
    "B700",
    "B7000",
    "B800",
    "Bronco",
    "Bronco II",
    "Bronco Sport",
    "C-Max",
    "C600",
    "C700",
    "C7000",
    "C800",
    "C8000",
    "CF6000",
    "CF7000",
    "CF8000",
    "CFT8000",
    "CL9000",
    "CLT9000",
    "CT800",
    "CT8000",
    "Contour",
    "Courier",
    "Crown Victoria",
    "E-100",
    "E-150",
    "E-250",
    "E-350",
    "E-450",
    "E-550",
    "Ecosport",
    "Edge",
    "Escape",
    "Escort",
    "Excursion",
    "Expedition",
    "Expedition EL",
    "Expedition MAX",
    "Explorer",
    "Explorer Sport",
    "Explorer Sport Trac",
    "F-100",
    "F-150",
    "F-150 Heritage",
    "F-250",
    "F-350",
    "F-450",
    "F-550",
    "F-590",
    "F-600",
    "F-650",
    "F-700",
    "F-750",
    "F-800",
    "F-Super Duty",
    "F6000",
    "F7000",
    "F8000",
    "FT800",
    "FT8000",
    "FT900",
    "Fairmont",
    "Festiva",
    "Fiesta",
    "Five Hundred",
    "Flex",
    "Focus",
    "Freestar",
    "Freestyle",
    "Fusion",
    "GT",
    "GT MKII",
    "Granada",
    "L800",
    "L8000",
    "L8501",
    "L8511",
    "L8513",
    "L9000",
    "L9501",
    "L9511",
    "L9513",
    "L9522",
    "LA8000",
    "LA9000",
    "LL9000",
    "LLA9000",
    "LLS9000",
    "LN600",
    "LN700",
    "LN7000",
    "LN800",
    "LN8000",
    "LN9000",
    "LNT800",
    "LNT8000",
    "LNT9000",
    "LS8000",
    "LS9000",
    "LT800",
    "LT8000",
    "LT8501",
    "LT8511",
    "LT8513",
    "LT9000",
    "LT9501",
    "LT9511",
    "LT9513",
    "LT9522",
    "LTA9000",
    "LTD",
    "LTL9000",
    "LTLA9000",
    "LTLS9000",
    "LTS8000",
    "LTS9000",
    "Laser",
    "Maverick",
    "Motorhome Chassis",
    "Mustang",
    "Mustang GTD",
    "Mustang Mach-E",
    "P600",
    "P700",
    "P800",
    "Probe",
    "Ranger",
    "Recreational Vehicle",
    "Taurus",
    "Taurus X",
    "Tempo",
    "Thunderbird",
    "Transit",
    "Transit Connect",
    "Windstar",
    "ZX2"
  ],
  "GEO": [
    "Metro",
    "Prizm",
    "Spectrum",
    "Sprint",
    "Storm",
    "Tracker"
  ],
  "GMC": [
    "Acadia",
    "Aluminum Tilt",
    "Bus Chassis",
    "C/K Pickup",
    "C5",
    "C6",
    "C7",
    "Caballero",
    "Canyon",
    "Cruise Origin AV",
    "Electric Vehicle",
    "Envoy",
    "Forward Control",
    "GMT-400",
    "Geo Tracker",
    "Heavy Conventional",
    "Hi-Cube",
    "Hummer EV Pickup",
    "Hummer EV SUV",
    "Jimmy",
    "Jimmy Utility",
    "Magna Van",
    "Motorhome Chassis",
    "P Truck Forward",
    "R Conventional",
    "Rally",
    "S15 Pickup",
    "S15 Utility",
    "S6",
    "Safari",
    "Savana",
    "Sierra",
    "Sierra EV",
    "Sierra HD",
    "Sierra Limited",
    "Sonoma",
    "Suburban",
    "Terrain",
    "V Conventional",
    "Value Van",
    "Vandura",
    "Yukon",
    "Yukon XL"
  ],
  "HONDA": [
    "Accord",
    "Accord Crosstour",
    "CR-V",
    "CR-Z",
    "Civic",
    "Civic Si",
    "Civic Type R",
    "Clarity",
    "Crosstour",
    "EV Plus",
    "Element",
    "FCX Clarity",
    "Fit",
    "HR-V",
    "Insight",
    "Odyssey",
    "Passport",
    "Pilot",
    "Prelude",
    "Prologue",
    "Ridgeline",
    "S2000",
    "del Sol"
  ],
  "HUMMER": [
    "H1",
    "H2",
    "H3",
    "H3T"
  ],
  "HYUNDAI": [
    "Accent",
    "Azera",
    "Elantra",
    "Elantra GT",
    "Elantra N",
    "Elantra Touring",
    "Entourage",
    "Equus",
    "Excel",
    "Genesis",
    "Genesis Coupe",
    "IONIQ 5 N",
    "Ioniq",
    "Ioniq 5",
    "Ioniq 6",
    "Kona",
    "Kona Electric",
    "Kona N",
    "Nexo",
    "Palisade",
    "Pony",
    "Santa Cruz",
    "Santa Fe",
    "Santa Fe Sport",
    "Santa Fe XL",
    "Scoupe",
    "Sonata",
    "Stellar",
    "Tiburon",
    "Tucson",
    "Veloster",
    "Veloster N",
    "Venue",
    "Veracruz",
    "XG300",
    "XG350",
    "Xcient"
  ],
  "INFINITI": [
    "EX35",
    "FX35",
    "FX37",
    "FX45",
    "FX50",
    "G20",
    "G25",
    "G35",
    "G37",
    "I30",
    "I35",
    "J30",
    "JX35",
    "M30",
    "M35",
    "M35h",
    "M37",
    "M45",
    "M56",
    "Q40",
    "Q45",
    "Q50",
    "Q60",
    "Q70",
    "Q70L",
    "QX30",
    "QX4",
    "QX50",
    "QX55",
    "QX56",
    "QX60",
    "QX70",
    "QX80"
  ],
  "ISUZU": [
    "Amigo",
    "Ascender",
    "Axiom",
    "F6",
    "F7",
    "FRR",
    "FSR",
    "FTR/FVR",
    "FTR/FVR/EVR",
    "H-Series",
    "Hombre",
    "I-Mark",
    "IMPULSE",
    "NPR",
    "NPR/NPR-HD",
    "NQR",
    "NQR/NRR",
    "NRR",
    "Oasis",
    "Pickup",
    "Rodeo",
    "Rodeo/Amigo",
    "Stylus",
    "T6F",
    "T7F",
    "T8F",
    "Trooper",
    "Trooper II",
    "VehiCross",
    "i-280",
    "i-290",
    "i-350",
    "i-370"
  ],
  "JAGUAR": [
    "E-PACE",
    "F-PACE",
    "F-TYPE",
    "I-PACE",
    "S-Type",
    "Vanden Plas",
    "X-Type",
    "XE",
    "XF",
    "XJ",
    "XJ12",
    "XJ6",
    "XJ8",
    "XJR",
    "XJS",
    "XK",
    "XK8"
  ],
  "JEEP": [
    "CJ-5",
    "CJ-6",
    "CJ-7",
    "CJ-8 Scrambler",
    "Cherokee",
    "Comanche",
    "Commander",
    "Compass",
    "Gladiator",
    "Grand Cherokee",
    "Grand Cherokee L",
    "Grand Wagoneer",
    "Grand Wagoneer L",
    "J-10",
    "J-20",
    "Liberty",
    "Patriot",
    "Renegade",
    "Wagoneer",
    "Wagoneer L",
    "Wagoneer S",
    "Wrangler",
    "Wrangler JK"
  ],
  "KARMA": [
    "Atlantic",
    "GS-6",
    "Gyesera",
    "Karma",
    "Kaveya",
    "Revero",
    "Revero GT"
  ],
  "KIA": [
    "Amanti",
    "Borrego",
    "Cadenza",
    "Carnival",
    "EV6",
    "EV9",
    "Forte",
    "Forte Koup",
    "K4",
    "K5",
    "K900",
    "Niro",
    "Optima",
    "Rio",
    "Rondo",
    "Sedona",
    "Seltos",
    "Sephia",
    "Sephia II/Spectra",
    "Sorento",
    "Soul",
    "Soul EV",
    "Spectra",
    "Sportage",
    "Stinger",
    "Telluride"
  ],
  "LAMBORGHINI": [
    "147",
    "Aventador",
    "Diablo",
    "Gallardo",
    "Huracan",
    "Murcielago",
    "Revuelto",
    "Roadster",
    "URUS"
  ],
  "LAND ROVER": [
    "Defender",
    "Discovery",
    "Discovery Sport",
    "Freelander",
    "LR2",
    "LR3",
    "LR4",
    "New Range Rover",
    "Range Rover",
    "Range Rover Evoque",
    "Range Rover Sport",
    "Range Rover Velar"
  ],
  "LEXUS": [
    "CT",
    "ES",
    "GS",
    "GX",
    "HS",
    "IS",
    "LC",
    "LFA",
    "LS",
    "LX",
    "NX",
    "RC",
    "RX",
    "RZ",
    "SC",
    "TX",
    "UX"
  ],
  "LINCOLN": [
    "Aviator",
    "Blackwood",
    "Continental",
    "Corsair",
    "LS",
    "MKC",
    "MKS",
    "MKT",
    "MKX",
    "MKZ",
    "Mark",
    "Mark LT",
    "Nautilus",
    "Navigator",
    "Navigator L",
    "Town Car",
    "Zephyr"
  ],
  "LOTUS": [
    "2-Eleven",
    "340R",
    "ELETRE",
    "Eagle",
    "Eclat",
    "Elan",
    "Eleven",
    "Elise",
    "Elite",
    "Emira",
    "Esprit",
    "Europa",
    "Evora",
    "Exige",
    "MEL",
    "Monaco",
    "Monza",
    "Spa",
    "Turbo Esprit"
  ],
  "LUCID": [
    "Air",
    "Gravity"
  ],
  "MASERATI": [
    "228",
    "430",
    "Biturbo",
    "Coupe",
    "Ghibli",
    "Grancabrio",
    "Granturismo",
    "Grecale",
    "Levante",
    "MC20",
    "Merak",
    "Quattroporte",
    "Spyder",
    "TC"
  ],
  "MAYBACH": [
    "57",
    "62"
  ],
  "MAZDA": [
    "323",
    "626",
    "929",
    "B-Series",
    "CX-3",
    "CX-30",
    "CX-5",
    "CX-50",
    "CX-7",
    "CX-70",
    "CX-9",
    "CX-90",
    "GLC",
    "MPV",
    "MX-3",
    "MX-30",
    "MX-5",
    "MX-6",
    "Mazda2",
    "Mazda3",
    "Mazda5",
    "Mazda6",
    "Millenia",
    "Navajo",
    "Protege",
    "RX-7",
    "RX-8",
    "Tribute"
  ],
  "MCLAREN": [
    "540C",
    "570GT",
    "570S",
    "600LT",
    "620R",
    "625C",
    "650S",
    "675LT",
    "720S",
    "750S",
    "765LT",
    "ARTURA",
    "ELVA",
    "GT",
    "GTS",
    "MP4-12C",
    "P1",
    "SENNA",
    "SENNA GTR"
  ],
  "MERCEDES-BENZ": [
    "190",
    "240",
    "260",
    "280",
    "300",
    "350",
    "380",
    "400",
    "420",
    "500",
    "560",
    "600",
    "A-Class",
    "AMG GT",
    "B-Class",
    "C-Class",
    "CL-Class",
    "CLA-Class",
    "CLE",
    "CLK-Class",
    "CLS-Class",
    "E-Class",
    "EQB-Class",
    "EQE-Class SUV",
    "EQE-Class Sedan",
    "EQS-Class SUV",
    "EQS-Class Sedan",
    "G-Class",
    "GL-Class",
    "GLA-Class",
    "GLB-Class",
    "GLC-Class",
    "GLE-Class",
    "GLK-Class",
    "GLS-Class",
    "L1013",
    "L1113",
    "L1116",
    "L1117",
    "L1316",
    "L1317",
    "L1319",
    "L1418",
    "L1419",
    "LP1219",
    "LP1419",
    "LPS1525",
    "M-Class",
    "ML-Class",
    "Metris",
    "R-Class",
    "S-Class",
    "SL-Class",
    "SLC-Class",
    "SLK-Class",
    "SLR McLaren",
    "SLS-Class",
    "Sprinter",
    "eSprinter"
  ],
  "MERCURY": [
    "Capri",
    "Cougar",
    "Grand Marquis",
    "Lynx",
    "MARQUIS",
    "Marauder",
    "Mariner",
    "Milan",
    "Montego",
    "Monterey",
    "Mountaineer",
    "Mystique",
    "Sable",
    "Topaz",
    "Tracer",
    "Villager",
    "Zephyr"
  ],
  "MINI": [
    "Clubman",
    "Cooper",
    "Cooper Convertible",
    "Cooper Coupe",
    "Cooper Roadster",
    "Countryman",
    "Hardtop",
    "Paceman"
  ],
  "MITSUBISHI": [
    "3000GT",
    "Cordia",
    "Diamante",
    "Eclipse",
    "Eclipse Cross",
    "Endeavor",
    "Expo",
    "Galant",
    "Lancer",
    "Lancer Evolution",
    "Lancer SportBack",
    "Mighty Max",
    "Mirage",
    "Mirage G4",
    "Montero",
    "Montero Sport",
    "Outlander",
    "Outlander Sport",
    "Precis",
    "RVR",
    "Raider",
    "SP",
    "SPX",
    "Sigma",
    "Space Wagon",
    "Starion",
    "Tredia",
    "Van",
    "Wagon",
    "i-MiEV"
  ],
  "NISSAN": [
    "200SX",
    "240SX",
    "300ZX",
    "350Z",
    "370Z",
    "ARIYA",
    "Altima",
    "Altra",
    "Altra-EV",
    "Armada",
    "Axxess",
    "Cube",
    "Frontier",
    "GT-R",
    "Juke",
    "Kicks",
    "Kicks MPV",
    "Kicks Play",
    "Leaf",
    "Maxima",
    "Micra",
    "Murano",
    "NISSAN Z",
    "NV",
    "NV200",
    "NX",
    "PULSAR",
    "Pathfinder",
    "Pickup",
    "Quest",
    "Rogue",
    "Rogue Select",
    "Rogue Sport",
    "Sentra",
    "Sentra Classic",
    "Stanza",
    "Stanza Wagon",
    "Titan",
    "Van",
    "Versa",
    "Versa Note",
    "X-Trail",
    "Xterra"
  ],
  "OLDSMOBILE": [
    "Achieva",
    "Alero",
    "Aurora",
    "Bravada",
    "Custom Cruiser",
    "Cutlass",
    "Cutlass Calais",
    "Cutlass Ciera",
    "Cutlass Cruiser",
    "Cutlass Salon",
    "Cutlass Supreme",
    "Delta 88",
    "Eighty Eight (88)",
    "Firenza",
    "Intrigue",
    "LSS",
    "Ninety Eight (98)",
    "Omega",
    "Regency",
    "Silhouette",
    "Toronado"
  ],
  "PETERBILT": [
    "200",
    "210",
    "220",
    "310",
    "320",
    "325",
    "330",
    "335",
    "337",
    "340",
    "348",
    "349",
    "352",
    "353",
    "357",
    "359",
    "362",
    "363",
    "365",
    "367",
    "372",
    "375",
    "376",
    "377",
    "378",
    "379",
    "382",
    "384",
    "385",
    "386",
    "387",
    "388",
    "389",
    "397",
    "476",
    "477",
    "520",
    "535",
    "536",
    "537",
    "548",
    "567",
    "579",
    "587",
    "589",
    "Medium Duty COE"
  ],
  "PEUGEOT": [
    "405",
    "504",
    "505",
    "604"
  ],
  "PLYMOUTH": [
    "Acclaim",
    "Arrow",
    "Breeze",
    "CARAVELLE",
    "CONQUEST",
    "Champ",
    "Colt",
    "GRAN FURY",
    "Grand Voyager",
    "HORIZON",
    "Laser",
    "Neon",
    "Prowler",
    "RELIANT",
    "SAPPORO",
    "Scamp",
    "Sundance",
    "TURISMO",
    "Trailduster",
    "Voyager"
  ],
  "PONTIAC": [
    "6000",
    "Acadian",
    "Aztek",
    "Bonneville",
    "Catalina",
    "Fiero",
    "Firebird",
    "Firefly",
    "G3",
    "G5",
    "G6",
    "G8",
    "GTO",
    "Grand AM",
    "Grand Lemans",
    "Grand Prix",
    "J2000",
    "Laurentian",
    "Lemans",
    "Matiz",
    "Montana",
    "Montana SV6",
    "Parisienne",
    "Phoenix",
    "Pursuit",
    "Safari",
    "Solstice",
    "Sunbird",
    "Sunbird 2000",
    "Sunburst",
    "Sunfire",
    "T1000",
    "Tempest",
    "Torrent",
    "Trans Sport",
    "Vibe",
    "Wave"
  ],
  "PORSCHE": [
    "718 Boxster",
    "718 Cayman",
    "718 Spyder",
    "911",
    "918",
    "924",
    "928",
    "944",
    "968",
    "Boxster",
    "Cayenne",
    "Cayman",
    "Macan",
    "Panamera",
    "Taycan"
  ],
  "RAM": [
    "1500",
    "2500",
    "3500",
    "4000",
    "4500",
    "5500",
    "Cargo Van",
    "ProMaster 1500",
    "ProMaster 2500",
    "ProMaster 3500",
    "Promaster City"
  ],
  "RIVIAN": [
    "EDV",
    "R1S",
    "R1T",
    "RCV"
  ],
  "ROLLS-ROYCE": [
    "Camargue",
    "Corniche",
    "Cullinan",
    "Dawn",
    "Flying Spur",
    "Ghost",
    "Park Ward",
    "Phantom",
    "Silver Dawn",
    "Silver Seraph",
    "Silver Spirit",
    "Silver Spur",
    "Spectre",
    "Touring Limousine",
    "Wraith"
  ],
  "SAAB": [
    "9-2X",
    "9-3",
    "9-4x",
    "9-5",
    "9-7X",
    "900",
    "9000"
  ],
  "SATURN": [
    "Astra",
    "Aura",
    "Ion",
    "L200",
    "L300",
    "LS",
    "LS1",
    "LS2",
    "LW1",
    "LW2",
    "LW200",
    "LW300",
    "Outlook",
    "Relay",
    "SC1",
    "SC2",
    "SL",
    "SL1",
    "SL2",
    "SL3",
    "SW1",
    "SW2",
    "Sky",
    "Vue"
  ],
  "SHELBY": [
    "Cobra",
    "GT"
  ],
  "SMART": [
    "EQ Fortwo",
    "Fortwo",
    "Fortwo Electric Drive",
    "smart"
  ],
  "SPYKER": [
    "C12",
    "C8",
    "D8/D12"
  ],
  "SUBARU": [
    "Ascent",
    "B9 Tribeca",
    "BRZ",
    "Baja",
    "Brat",
    "Crosstrek",
    "DL",
    "Forester",
    "GL",
    "GL-10",
    "GLF",
    "Impreza",
    "Justy",
    "Legacy",
    "Loyale",
    "Outback",
    "RX",
    "SVX",
    "Solterra",
    "Standard",
    "WRX",
    "XT",
    "XT6",
    "XV CrossTrek"
  ],
  "SUZUKI": [
    "Aerio",
    "Equator",
    "Esteem",
    "Forenza",
    "Forsa",
    "Grand Vitara",
    "Grand Vitara XL-7",
    "Kizashi",
    "Reno",
    "SX4",
    "Samurai",
    "Sidekick",
    "Sidekick Sport",
    "Swift",
    "Verona",
    "Vitara",
    "X-90",
    "XL7"
  ],
  "TESLA": [
    "Cybertruck",
    "Model 3",
    "Model S",
    "Model X",
    "Model Y",
    "Roadster",
    "Semi"
  ],
  "TOYOTA": [
    "4-Runner",
    "86",
    "Avalon",
    "C-HR",
    "COROLLA iM",
    "Camry",
    "Camry Solara",
    "Cargo Van",
    "Celica",
    "Corolla",
    "Corolla Cross",
    "Corolla Matrix",
    "Corona",
    "Cressida",
    "Crown",
    "Crown Signia",
    "Echo",
    "FCHV-adv",
    "FJ Cruiser",
    "GR Corolla",
    "GR86",
    "Grand Highlander",
    "Highlander",
    "Land Cruiser",
    "MR2",
    "Mirai",
    "Paseo",
    "Pick-Up",
    "Previa",
    "Prius",
    "Prius C",
    "Prius Plug-in",
    "Prius Prime",
    "Prius V",
    "RAV4",
    "RAV4 Prime",
    "Scion FR-S",
    "Scion iA",
    "Scion iM",
    "Scion iQ",
    "Scion tC",
    "Scion xA",
    "Scion xB",
    "Scion xD",
    "Sequoia",
    "Sienna",
    "Starlet",
    "Supra",
    "T100",
    "Tacoma",
    "Tercel",
    "Tundra",
    "Van",
    "Venza",
    "Yaris",
    "Yaris iA",
    "bZ4X"
  ],
  "TRIUMPH": [
    "TR7",
    "TR8"
  ],
  "VOLVO": [
    "240 Series",
    "260 Series",
    "740 Series",
    "760 Series",
    "780 Series",
    "850 Series",
    "940 Series",
    "960 Series",
    "C30",
    "C40",
    "C70",
    "C70 / C30",
    "Cab Behind Engine",
    "Cab Over Engine HT",
    "Cab Over Engine LT",
    "EC40",
    "EX30",
    "EX40",
    "EX90",
    "F12 w/F7 Cab",
    "F6 w/F7 Cab",
    "S40",
    "S60",
    "S60 Cross Country",
    "S70",
    "S80",
    "S90",
    "V40",
    "V50",
    "V60",
    "V60CC",
    "V70",
    "V90",
    "V90CC",
    "VS",
    "VT",
    "XC40",
    "XC60",
    "XC70",
    "XC90"
  ],
  "YUGO": [
    "102, GV",
    "Yugo 45",
    "Yugo 55",
    "Yugo 65"
  ],

  // ── LATAM / Colombia market makes ──────────────────────────────────────────
  "RENAULT": [
    "Captur", "Clio", "Duster", "Fluence", "Kangoo", "Kardian", "Koleos",
    "Kwid", "Logan", "Megane", "Oroch", "Sandero", "Scenic", "Stepway",
    "Symbol", "Twingo", "Zoe"
  ],
  "VOLKSWAGEN": [
    "Amarok", "Beetle", "Caravelle", "Golf", "Jetta", "Multivan", "Passat",
    "Phaeton", "Polo", "T-Cross", "T-Roc", "Taos", "Tiguan", "Touareg",
    "Touran", "Transporter", "Vento", "Virtus"
  ],
  "CHERY": [
    "Arrizo 5", "Arrizo 6", "Arrizo 8", "Fulwin", "QQ", "Tiggo 2",
    "Tiggo 2 Pro", "Tiggo 3", "Tiggo 4", "Tiggo 4 Pro", "Tiggo 5",
    "Tiggo 7", "Tiggo 7 Pro", "Tiggo 8", "Tiggo 8 Pro"
  ],
  "JAC": [
    "iEV6E", "iEV7S", "J2", "J3", "J4", "J7", "S3", "S4", "S5", "S7",
    "Sei 2", "Sei 3", "Sei 4", "T6", "T8", "X200"
  ],
  "HAVAL": [
    "Dargo", "F7", "H1", "H2", "H4", "H6", "H9", "Jolion", "M6", "Shenshou"
  ],
  "GWM": [
    "Haval H2", "Haval H6", "Haval Jolion", "Poer", "Wingle 5", "Wingle 7"
  ],
  "BYD": [
    "Atto 3", "Dolphin", "F3", "Han", "King", "Seal", "Song", "Song Plus",
    "Tan", "Tang", "Yuan Plus"
  ],
  "GEELY": [
    "Azkarra", "Coolray", "EC7", "Emgrand", "Emgrand X7", "MK", "Okavango",
    "Tugella", "Vision"
  ],
  "MAHINDRA": [
    "Bolero", "KUV100", "Roxor", "Scorpio", "Scorpio N", "TUV300",
    "XUV300", "XUV400", "XUV500", "XUV700"
  ],
  "SSANGYONG": [
    "Actyon", "Actyon Sports", "Korando", "Musso", "Rexton", "Rodius",
    "Tivoli", "Tivoli XLV", "Torres"
  ],
  "CITROEN": [
    "Berlingo", "C-Elysée", "C3", "C3 Aircross", "C4", "C4 Cactus",
    "C5 Aircross", "Jumper", "Jumpy", "Spacetourer"
  ],
  "SKODA": [
    "Fabia", "Karoq", "Kodiaq", "Octavia", "Rapid", "Scala", "Superb", "Yeti"
  ],
  "SEAT": [
    "Arona", "Ateca", "Ibiza", "Leon", "Tarraco"
  ],
  "DFSK": [
    "C31", "C35", "EC35", "Glory 330", "Glory 500", "Glory 560", "Glory 580",
    "K01H", "V21", "V27"
  ],
  "LIFAN": [
    "320", "520", "620", "720", "820", "Foison", "Myway", "X50", "X60", "X70"
  ]
}

export const YEAR_RANGE_BY_MAKE: Record<string, { first: number; last: number }> = {
  "ACURA": {
    "first": 1985,
    "last": 2026
  },
  "ALFA ROMEO": {
    "first": 1981,
    "last": 2026
  },
  "AM GENERAL": {
    "first": 2013,
    "last": 2026
  },
  "ASTON MARTIN": {
    "first": 1981,
    "last": 2026
  },
  "AUDI": {
    "first": 1981,
    "last": 2026
  },
  "BENTLEY": {
    "first": 1984,
    "last": 2026
  },
  "BMW": {
    "first": 1981,
    "last": 2026
  },
  "BUGATTI": {
    "first": 1994,
    "last": 2026
  },
  "BUICK": {
    "first": 1981,
    "last": 2026
  },
  "CADILLAC": {
    "first": 1981,
    "last": 2026
  },
  "CHEVROLET": {
    "first": 1981,
    "last": 2026
  },
  "CHRYSLER": {
    "first": 1981,
    "last": 2026
  },
  "DAEWOO": {
    "first": 1997,
    "last": 2008
  },
  "DAIHATSU": {
    "first": 1985,
    "last": 2026
  },
  "DAIMLER": {
    "first": 2019,
    "last": 2026
  },
  "DATSUN": {
    "first": 1981,
    "last": 1983
  },
  "DELOREAN": {
    "first": 1981,
    "last": 1986
  },
  "DODGE": {
    "first": 1981,
    "last": 2026
  },
  "FERRARI": {
    "first": 1981,
    "last": 2026
  },
  "FIAT": {
    "first": 1981,
    "last": 2026
  },
  "FISKER": {
    "first": 2011,
    "last": 2026
  },
  "FORD": {
    "first": 1981,
    "last": 2026
  },
  "GEO": {
    "first": 1985,
    "last": 1997
  },
  "GMC": {
    "first": 1981,
    "last": 2026
  },
  "HONDA": {
    "first": 1981,
    "last": 2026
  },
  "HUMMER": {
    "first": 1991,
    "last": 2011
  },
  "HYUNDAI": {
    "first": 1986,
    "last": 2026
  },
  "INFINITI": {
    "first": 1990,
    "last": 2026
  },
  "ISUZU": {
    "first": 1981,
    "last": 2026
  },
  "JAGUAR": {
    "first": 1981,
    "last": 2026
  },
  "JEEP": {
    "first": 1981,
    "last": 2026
  },
  "KARMA": {
    "first": 2015,
    "last": 2026
  },
  "KIA": {
    "first": 1993,
    "last": 2026
  },
  "LAMBORGHINI": {
    "first": 1989,
    "last": 2026
  },
  "LAND ROVER": {
    "first": 1985,
    "last": 2026
  },
  "LEXUS": {
    "first": 1990,
    "last": 2026
  },
  "LINCOLN": {
    "first": 1981,
    "last": 2026
  },
  "LOTUS": {
    "first": 1981,
    "last": 2026
  },
  "LUCID": {
    "first": 2022,
    "last": 2026
  },
  "MASERATI": {
    "first": 1981,
    "last": 2026
  },
  "MAYBACH": {
    "first": 2003,
    "last": 2026
  },
  "MAZDA": {
    "first": 1981,
    "last": 2026
  },
  "MCLAREN": {
    "first": 2009,
    "last": 2026
  },
  "MERCEDES-BENZ": {
    "first": 1981,
    "last": 2026
  },
  "MERCURY": {
    "first": 1981,
    "last": 2011
  },
  "MINI": {
    "first": 2002,
    "last": 2026
  },
  "MITSUBISHI": {
    "first": 1983,
    "last": 2026
  },
  "NISSAN": {
    "first": 1981,
    "last": 2026
  },
  "OLDSMOBILE": {
    "first": 1981,
    "last": 2004
  },
  "PETERBILT": {
    "first": 1981,
    "last": 2026
  },
  "PEUGEOT": {
    "first": 1981,
    "last": 2026
  },
  "PLYMOUTH": {
    "first": 1981,
    "last": 2026
  },
  "PONTIAC": {
    "first": 1981,
    "last": 2010
  },
  "PORSCHE": {
    "first": 1981,
    "last": 2026
  },
  "RAM": {
    "first": 2012,
    "last": 2026
  },
  "RIVIAN": {
    "first": 2022,
    "last": 2026
  },
  "ROLLS-ROYCE": {
    "first": 1981,
    "last": 2026
  },
  "SAAB": {
    "first": 1981,
    "last": 2026
  },
  "SATURN": {
    "first": 1991,
    "last": 2010
  },
  "SHELBY": {
    "first": 2022,
    "last": 2026
  },
  "SMART": {
    "first": 2000,
    "last": 2026
  },
  "SPYKER": {
    "first": 2002,
    "last": 2026
  },
  "SUBARU": {
    "first": 1981,
    "last": 2026
  },
  "SUZUKI": {
    "first": 1981,
    "last": 2026
  },
  "TESLA": {
    "first": 2008,
    "last": 2026
  },
  "TOYOTA": {
    "first": 1981,
    "last": 2026
  },
  "TRIUMPH": {
    "first": 1981,
    "last": 2026
  },
  "VOLVO": {
    "first": 1981,
    "last": 2026
  },
  "YUGO": {
    "first": 1985,
    "last": 2026
  }
}
